import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://howlingtesters.pl/party/');
  await page.getByRole('button', { name: 'Accept All' }).click();
  await page.getByRole('textbox', { name: 'Imię postaci:' }).click();
  await page.getByRole('textbox', { name: 'Imię postaci:' }).fill('AgaWojownik');
  await page.getByRole('img', { name: 'Wojownik' }).click();
  await page.getByRole('spinbutton', { name: 'Siła:' }).click();
  await page.getByRole('spinbutton', { name: 'Siła:' }).fill('20');
  await page.getByRole('spinbutton', { name: 'Zdrowie:' }).click();
  await page.getByRole('spinbutton', { name: 'Zdrowie:' }).fill('15');
  await page.getByRole('button', { name: 'Dodaj postać' }).click();
  await page.getByRole('textbox', { name: 'Imię postaci:' }).click();
  await page.getByRole('textbox', { name: 'Imię postaci:' }).fill('AgaŁotrzyk');
  await page.getByRole('img', { name: 'Łotrzyk' }).click();
  await page.getByRole('spinbutton', { name: 'Spryt:' }).click();
  await page.getByRole('spinbutton', { name: 'Spryt:' }).fill('20');
  await page.getByRole('spinbutton', { name: 'Energia:' }).click();
  await page.getByRole('spinbutton', { name: 'Energia:' }).fill('15');
  await page.getByRole('button', { name: 'Dodaj postać' }).click();
  await page.getByRole('textbox', { name: 'Imię postaci:' }).click();
  await page.getByRole('textbox', { name: 'Imię postaci:' }).fill('AgaCzarodziej');
  await page.getByRole('spinbutton', { name: 'Spryt:' }).click();
  await page.getByRole('spinbutton', { name: 'Spryt:' }).fill('20');
  await page.getByRole('spinbutton', { name: 'Siła:' }).click();
  await page.getByRole('spinbutton', { name: 'Siła:' }).fill('13');
  await page.getByRole('button', { name: 'Dodaj postać' }).click();
  await page.getByRole('button', { name: 'Zamknij' }).click();
  await page.getByRole('spinbutton', { name: 'Siła:' }).click();
  await page.getByRole('spinbutton', { name: 'Siła:' }).fill('15');
  await page.getByRole('button', { name: 'Dodaj postać' }).click();
  await page.getByRole('button', { name: 'Zamknij' }).click();
  await page.getByRole('img', { name: 'Czarodziej' }).click();
  await page.getByRole('button', { name: 'Dodaj postać' }).click();
  await page.getByRole('textbox', { name: 'Imię postaci:' }).click();
  await page.getByRole('textbox', { name: 'Imię postaci:' }).fill('AgaZwiadowca');
  await page.getByRole('img', { name: 'Zwiadowca' }).click();
  await page.getByRole('spinbutton', { name: 'Energia:' }).click();
  await page.getByRole('spinbutton', { name: 'Energia:' }).fill('20');
  await page.getByRole('spinbutton', { name: 'Spryt:' }).click();
  await page.getByRole('spinbutton', { name: 'Spryt:' }).fill('15');
  await page.getByRole('button', { name: 'Dodaj postać' }).click();
  await page.getByRole('textbox', { name: 'Imię postaci:' }).click();
  await page.getByRole('textbox', { name: 'Imię postaci:' }).fill('SuperAga');
  await page.getByText('Czarodziej', { exact: true }).click();
  await page.getByRole('spinbutton', { name: 'Spryt:' }).click();
  await page.getByRole('spinbutton', { name: 'Spryt:' }).fill('20');
  await page.getByRole('spinbutton', { name: 'Energia:' }).click();
  await page.getByRole('spinbutton', { name: 'Energia:' }).fill('12');
  await page.getByRole('button', { name: 'Dodaj postać' }).click();
  await expect(page.locator('#popup-title')).toContainText('Limit postaci');
  await expect(page.locator('#popup-message')).toContainText('Możesz mieć maksymalnie 4 postacie. Usuń jedną, aby dodać nową.');
  await page.getByRole('button', { name: 'Zamknij' }).click();
});